Non stop tickets
if137angular/if137angular pull request #14
Opened 2022-01-05 15:31 UTC by Petsoliak

2022-01-05 19:39 UTC, olena-dev commented on src/app/app.component.ts
> -    this.store.dispatch([new GetCountries(), new GetCities(), new GetAirports()]);
revert this.

2022-01-05 19:39 UTC, olena-dev commented on src/app/components/forTest/first/first.component.html
> +<app-non-stop-tickets></app-non-stop-tickets>
add your component to the route and nav menu

2022-01-10 12:02 UTC, if137angular requested changes

2022-01-10 12:02 UTC, if137angular commented on src/app/components/non-stop-tickets/non-stop-tickets.component.ts
> +// import { GetAirports, GetCities, GetCountries } from 'src/app/store/request-data.action';
remove commented code

2022-01-10 12:02 UTC, if137angular commented on src/app/components/non-stop-tickets/non-stop-tickets.component.ts
> +    // this.store.dispatch([new GetCountries(), new GetAirports(), new GetCities()]);
remove commented code in all places

2022-01-10 12:02 UTC, if137angular commented on src/app/components/non-stop-tickets/non-stop-tickets.component.ts
> +      console.log(res);
remove console.log

2022-01-10 12:02 UTC, if137angular commented on src/app/app.component.ts
> +  constructor() {
revert store and dispatch as it was before

2022-01-10 16:23 UTC, olena-dev approved these changes

2022-01-10 16:25 UTC, olena-dev approved these changes

2022-01-10 16:26 UTC, olena-dev approved these changes

2022-01-10 16:28 UTC, if137angular approved these changes

2022-01-10 23:02 UTC, merged